//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
